### PR TITLE
#34 - Add routing tools

### LINKED ISSUE #34: Add routing tools
Create tools for routes

### PR DESCRIPTION
**Pull request by PiotrFedak**
This PR aims to combine methods from HttpRequest, HttpResponse, Session, Authentication and Translation to better reflect the Routing trait.

This should close #34

### CODE REVIEW

**Comment by PiotrFedak** [comment]
I need someone to comment/give me opinion on this because the longer I look at it, the more I think it's a lot of code repetition and unnecessary trait to have.

**Comment by EwelinaSkrzypacz** [comment]
Sorry, by mistake

**Comment by EwelinaSkrzypacz** [comment]
Please resolve conflicts

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. In documentation, in `Overview` section, the `Routing` is missing

image

2. In the menu `Routing` is on the end but I noticed that all options are sorted alphabetically

image

3. Please look at the video below - when I want to see PHP code, in one case, the content stretches :point_down: 

https://github.com/user-attachments/assets/2af0350d-0a78-44e8-a6ed-33f3ed9717d8

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Pull request merged**
